<?php

/**
 * Class Harvey_Import_Model_Mysql4_Import
 */
class Harvey_Import_Model_Mysql4_Import extends Mage_Core_Model_Mysql4_Abstract {}

/**
 * Class Harvey_Import_Model_Resource_Import
 */
class Harvey_Import_Model_Resource_Import extends Mage_Core_Model_Mysql4_Abstract {}

/**
 * Class Harvey_Import_Model_Resource_Import2
 */
class Harvey_Import_Model_Resource_Import2 extends Mage_Core_Model_Resource_Abstract {}

/**
 * Class Mage_Core_Model_Resource_Abstract
 */
class Mage_Core_Model_Resource_Abstract {}

/**
 * Class Mage_Core_Model_Mysql4_Abstract
 */
class Mage_Core_Model_Mysql4_Abstract {}
