<?php

/**
 * Class Mage_Catalog_Model_Product
 */
class Mage_Catalog_Model_Product {}

/**
 * Class Varien_Object
 */
class Varien_Object {}

/**
 * Class Zend_Uri_Http
 */
class Zend_Uri_Http {}

/**
 * Class Enterprise_CatalogEvent_Model_Observer
 */
class Enterprise_CatalogEvent_Model_Observer {}

/**
 * Class My_Module_Model_Order
 */
class My_Module_Model_Order {}

$a = new Mage_Catalog_Model_Product();
$b = new Varien_Object();
$c = new Zend_Uri_Http();
$d = new Enterprise_CatalogEvent_Model_Observer;
$e = new My_Module_Model_Order;
